spring.jpa.hibernate.ddl-auto: create-drop

accounting:
  currency:
    rateprovider: bankOfRussiaCurrencyRateProviderImpl
    bankofrussia.language: en
  demo:
    count:
      category: 6
      currency: 4
      account: 4
      transaction: 200
    transaction:
      dateRangeBack: 6m
      dateRangeForward: 0d
      operationCountMin: 1
      operationCountMax: 4
      operationAmountMin: -10000
      operationAmountMax: 10000
