spring:
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: true
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate.id.new_generator_mappings: false

accounting.currency.rateprovider: europeanCentralBankCurrencyRateProviderImpl

logging.level:
  root: warn
  com.lonebytesoft.hamster.accounting: debug
  org.springframework: info
  org.hibernate: info
